package com.kkdev.crackie.db

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch

@Database(entities = [Fortune::class], version = 1, exportSchema = false)
abstract class FortuneDatabase : RoomDatabase() {

    abstract fun fortuneDao(): FortuneDao

    companion object {
        @Volatile
        private var INSTANCE: FortuneDatabase? = null

        fun getDatabase(context: Context): FortuneDatabase {
            return INSTANCE ?: synchronized(this) {
                val instance = Room.databaseBuilder(
                    context.applicationContext,
                    FortuneDatabase::class.java,
                    "fortune_database"
                )
                    .fallbackToDestructiveMigration()
                    .addCallback(FortuneDatabaseCallback(context))
                    .build()
                INSTANCE = instance
                instance
            }
        }
    }

    private class FortuneDatabaseCallback(private val context: Context) : RoomDatabase.Callback() {
        override fun onCreate(db: SupportSQLiteDatabase) {
            super.onCreate(db)
            INSTANCE?.let { database ->
                CoroutineScope(Dispatchers.IO).launch {
                    populateDatabase(database.fortuneDao())
                }
            }
        }

        suspend fun populateDatabase(fortuneDao: FortuneDao) {
            val initialFortunes = listOf(
                Fortune(text = "A small victory will brighten your day.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your kindness will be returned soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Something lost will find its way back to you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A friend will make you smile unexpectedly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel lighter after finishing one small task.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good news is on its way.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll have a reason to celebrate soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your patience will pay off soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A pleasant surprise will find you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll cross paths with good energy today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A small act of kindness will ripple far.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Trust that things are moving your way.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today’s effort builds tomorrow’s luck.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Something beautiful hides in plain sight.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A door will open where one once closed.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Focus brings clarity and calm.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your ideas will shine when shared.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Take a breath; everything is unfolding fine.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone is silently cheering for you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good timing will be on your side.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your calm presence will inspire others.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Smile—you’re closer than you think.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today is a good day to start again.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Appreciate small wins—they add up.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An unexpected laugh will heal your mood.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Listen twice, speak once.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your best ideas arrive in quiet moments.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Take a short walk—it’ll change everything.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Do one brave thing today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Be kind without reason—it comes back.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A clear mind opens new doors.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Don’t rush what needs time.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Something small will make you proud today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice beauty in an ordinary place.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will appreciate your effort.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A new idea will find you today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Take that first step—you’ll feel lighter.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You will find calm in unexpected moments.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Luck follows those who act with heart.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Do something kind for future you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Joy hides in your routine today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s words will stay with you—in a good way.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A challenge will reveal your strength.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today’s patience brings tomorrow’s reward.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good things take shape quietly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll soon laugh about what worried you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You radiate calm even when unsure.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s thinking kindly of you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Do one thing slower today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll meet positivity halfway.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An idea you forgot will return stronger.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Be still—clarity is on its way.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your humor will brighten someone’s mood.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Smile at the next stranger you see.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You will be the reason for someone’s calm.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A good habit will stick today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll hear something that changes your outlook.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "What you give returns multiplied.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Pat yourself on the back—you deserve it.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A moment of clarity will find you soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s good news will inspire you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel proud of a small improvement.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’re on the right track—keep walking.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Make time for one quiet joy today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find beauty in something old.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Something simple will feel profound today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your calm will solve more than your effort.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A lucky coincidence is approaching.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Be kind to yourself; it echoes outward.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice how far you’ve come.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Let curiosity lead for a while.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A quiet evening will recharge you deeply.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll laugh at a perfect moment today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Peace will arrive when you least expect.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Take the scenic route—it’s worth it.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good fortune hides in small beginnings.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A simple gesture will make your day.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your efforts are seen, even if not spoken.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You will make progress quietly today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An old worry will lose its weight.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Focus on joy, and luck will follow.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice a hidden opportunity.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You are stronger than you realize.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your presence will lift the room.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Keep going; the result will surprise you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good things start quietly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Something you feared will turn out fine.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today holds more potential than you think.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An unexpected smile will make your day.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Let go of one worry—it’s lighter without.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The answer you seek will appear simply.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Kindness will circle back soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A bit of luck hides in today’s routine.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Trust your gut—it’s been right lately.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A small decision will lead to joy.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your laughter will attract good energy.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Take the break—you’ve earned it.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s compliment will stay with you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll rediscover an old joy.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good vibes follow your focus.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your positive energy draws opportunity.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find clarity after rest.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll inspire someone unknowingly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A light mood brings lucky outcomes.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone you admire will notice you soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good luck hides in good habits.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "New inspiration will find you mid-day.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your patience is quietly shaping results.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A familiar place will feel brand new today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll end the day lighter than you began.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A casual chat will bring good ideas.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice beauty in someone’s words.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Something small will bring unexpected peace.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your inner calm will impress someone.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A small effort will have a big return.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today’s distraction may lead to discovery.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your focus will attract opportunity.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s kindness will restore your faith.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll laugh harder than you expect today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Let curiosity drive your choices today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good fortune hides behind a brave choice.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll solve a problem by doing less.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An answer will come when you stop looking.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’re about to receive a small but happy message.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your genuine smile will open a new door.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "What you imagine now can soon be real.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A stranger will brighten your day.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will thank you unexpectedly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The next sunrise holds promise for you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Peace follows your patience today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your idea will land perfectly on someone’s mind.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll rediscover something you love.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today’s detour leads to something better.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your calm will be contagious.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A surprise message will make you smile.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice luck in timing today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your humor will diffuse tension.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find meaning in something ordinary.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s honesty will strengthen your trust.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A soft approach will bring better results.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Something unexpected will feel perfectly timed.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A small risk will pay off kindly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll make progress in quiet ways today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your optimism will attract help.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A new routine will energize you soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your day will end better than it began.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll get an answer you didn’t know you needed.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s laughter will lift your mood.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A quiet moment will reset your energy.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good fortune follows steady effort.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today’s challenge will teach you grace.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll be pleasantly surprised by simplicity.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your calm decision will turn out best.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The universe is rearranging things in your favor.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll recall a good memory at the right time.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your next laugh will open new luck.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’re closer to success than you feel.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Patience will reveal what action can’t.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s kindness will change your pace.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good energy surrounds your next step.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A light heart will attract bright moments.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The right person will understand you easily today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your patience today plants future success.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find inspiration where you rest.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A forgotten plan will suddenly feel right again.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll realize how supported you are.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Something small will remind you of your worth.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your luck improves when you let go.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your confidence will spark someone else’s.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An honest word will bring relief today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The day will end with unexpected calm.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll see proof of your progress soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Joy will find you when you least expect.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel connected in an unexpected way.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The next compliment you receive will be sincere.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today’s pause will lead to clarity.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A creative spark will surprise you soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find reassurance in small signs.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will think of you with gratitude.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An old worry will fade quietly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll handle change with quiet strength.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your steady effort attracts hidden help.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll see beauty in imperfection today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A kind word will travel far today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find calm in unexpected places.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone new will feel instantly familiar.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your gratitude will multiply your luck.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A new idea will align perfectly soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll surprise yourself with how well it goes.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your positivity will turn a small moment golden.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll end the day proud of something small.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today’s calm brings tomorrow’s clarity.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice good timing at work today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your kindness will echo beyond today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll be exactly where you need to be.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s small gesture will mean a lot.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your mood will shape someone’s day—brightly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A coincidence today will feel magical.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your steady rhythm invites luck.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll see the good in an old story.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An old idea will finally make sense.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your energy today attracts understanding.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll realize peace was always near.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A bit of laughter will fix your mood.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today feels lighter for a reason.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find joy hiding in your schedule.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your next idea will come with ease.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A happy surprise hides in your routine.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll inspire calm by staying kind.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The next person you meet will bring luck.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your effort today plants long-term rewards.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice peace where stress once lived.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A clear answer is coming soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A new idea will spark joy today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll receive the clarity you’ve been waiting for.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A simple choice will lead to something good.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll hear exactly what you needed to hear.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A quiet start brings a bright finish.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice progress in the little things.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will bring positivity your way.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A tiny decision will unlock something big.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The moment you relax, good news arrives.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s kindness will surprise you today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll rediscover a reason to smile.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today’s calm will guide you through the week.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll receive good energy from unexpected places.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A missed chance will return at the right time.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your focus will bring clarity to others.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An ordinary task will feel meaningful today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice a shift in your luck soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A gentle word will create new trust.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll be grateful for today’s timing.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Something you’ve been waiting for is closer than it seems.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will admire your calm energy.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find inspiration in an unexpected sound.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A brief conversation will stick with you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The right word will arrive at the right time.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll soon understand what patience can do.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A forgotten dream will start feeling possible again.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find joy hiding in the in-between moments.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A random encounter will bring a smile.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll see why things took the time they did.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A plan will unfold smoother than expected.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll have the right words at the right time.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Something small will make today memorable.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your persistence will impress the right person.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A spark of creativity will visit you today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A moment of laughter will turn the day around.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll realize you’ve already grown past an old limit.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll soon receive confirmation of your progress.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone you help today will remember it.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice a happy coincidence by evening.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your next decision will bring peace.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The effort you make now will echo far.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll catch a glimpse of good luck.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your focus will clear the path ahead.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone nearby is rooting for your success.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today’s lesson will reveal itself later.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll soon see the benefit of slowing down.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A quiet smile will attract a kind response.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find peace through simplicity today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your curiosity will unlock something fun.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good fortune hides behind your current challenge.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll be pleasantly surprised by your own timing.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A little courage will bring a big smile.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will quote your words soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your next laugh will attract a good moment.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice how far you’ve come without realizing.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A simple act will create lasting joy.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s smile will make you pause happily.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find a new reason to be proud.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll catch a lucky moment between plans.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A soft tone will carry strong impact today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll rediscover an old motivation.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good things will happen when you share your ideas.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will mirror your positive energy.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An obstacle will show you your own strength.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll receive gentle encouragement today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your perspective will brighten a dull task.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A bit of joy will sneak into your schedule.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll be surprised how easy it feels to forgive.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s laughter will remind you of peace.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your current effort is building something unseen.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A gentle reminder will make you smile today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice the beauty of patience soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will appreciate your simple honesty.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll sense good energy in your next step.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A break you take today will bring inspiration.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find humor in something small.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your quiet confidence will be noticed.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel lighter after helping someone.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A short walk will shift your perspective.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll see luck in how things align today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s story will remind you of your own.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll sense opportunity where others see chance.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A good surprise will find you soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll realize how loved you truly are.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The right idea will find you when relaxed.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A bit of peace will arrive when you least expect.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll turn an ordinary moment into something special.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your curiosity will be rewarded with clarity.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s message will make your evening better.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice fortune in small coincidences.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your outlook will brighten someone else’s mood.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A surprise compliment will make your day.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll be exactly where good luck finds you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your patience will open the right door soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll see something ordinary in a new light.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A positive shift begins with today’s effort.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll experience a calm victory soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An old obstacle will feel smaller today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll realize something important without trying.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good energy follows your smallest decision.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll sense a lucky turn in conversation.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your actions today will echo kindly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll see progress in something you paused.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A peaceful moment will last longer than expected.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll soon feel in sync with the world around you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s advice will suddenly make sense.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A random smile will bring comfort today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice fortune hiding in your routine.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A new start will feel easier than you think.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find peace in something you used to rush.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A kind thought will come back to you soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll make progress without even realizing it.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will share something that inspires you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A quiet victory is still a victory.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your calm approach will solve a small problem.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A forgotten skill will come in handy soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel lighter after letting go of one worry.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your timing will be perfect without effort.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will remind you how capable you are.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll spot an easy solution to a hard task.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good things will grow from today’s choices.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll reconnect with someone at the right time.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A pleasant rhythm will return to your day.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel proud of how far you’ve come.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A chance encounter will bring good energy.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will appreciate your effort quietly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your good mood will be contagious today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A delay today will turn out to be lucky.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll recognize the beauty of patience.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A soft laugh will erase a small tension.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s kindness will set your tone for the day.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find the right words without planning.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A calm decision will bring lasting happiness.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll soon realize how steady you’ve become.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A short pause will reveal the answer you need.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll receive comfort from a familiar sound.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Today’s patience will open tomorrow’s doors.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel a calm confidence take over soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A lucky moment will hide in plain sight.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll gain clarity while doing something simple.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your steady rhythm will inspire someone nearby.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll rediscover a reason to keep believing.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A good surprise will replace an old worry.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice something small that means a lot.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your patience will turn effort into ease.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A friend’s message will arrive at the right time.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll see proof that your consistency works.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A lucky word will find its way to you today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s gesture will warm your heart.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll make a memory without realizing it.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good energy is quietly gathering for you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice balance returning to your path.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A thought from the past will bring comfort.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll be reminded that small wins matter.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A peaceful ending will come to something old.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel lucky without knowing why.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s words will linger in a good way.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll soon hear the answer you hoped for.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your good attitude will attract easy luck.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find relief where you least expect it.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s quiet support will mean everything.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A happy coincidence will brighten your mood.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll see potential where others see pause.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A good decision will come naturally today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll sense luck building behind the scenes.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone close will notice your effort soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your calmness will ripple through your day.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll enjoy a moment of pure contentment.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A small act will lead to a joyful moment.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll be reminded that peace is progress.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your focus will make something easier.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll reconnect with your sense of wonder.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A hint of luck will follow your next choice.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll sense balance returning to your plans.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A friendly gesture will brighten your path.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll catch yourself smiling for no reason.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your patience today will pay off soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A wave of gratitude will wash over you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will remind you what joy feels like.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll rediscover an old passion unexpectedly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A simple act will reveal hidden meaning.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll soon realize everything aligned for you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your steady pace will bring gentle success.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel inspired to try again.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A surprise idea will come during rest.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice your good habits paying off.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A new light will fall on something familiar.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll hear something that makes you hopeful.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s thoughtfulness will reach you today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find joy in helping quietly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A gentle surprise will close your day beautifully.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel lucky just to be where you are.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A warm memory will visit you unexpectedly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice peace following your choices.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good timing will make today smoother.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll be grateful for something simple soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A new rhythm will make your day feel right.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel harmony return at the right moment.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A familiar song will lift your spirit.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll quietly overcome something small today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Good energy will follow your calm choices.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll realize how simple joy can be.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s warmth will bring you comfort.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll get a sign that you’re on the right path.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A peaceful moment will feel like a reward.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your patience will be tested, then rewarded.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A moment of courage will change your week.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll turn an idea into a real step forward.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Your calm strength is your quiet superpower.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel luck following your intentions today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will thank you in an unexpected way.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your next small step will carry big weight.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll find purpose in something routine.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A thoughtful pause will guide you right.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone believes in you more than you know.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll soon feel proud of your patience.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your energy attracts good things today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A chance to shine will arrive quietly.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll get proof that kindness travels far.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A forgotten goal will feel exciting again.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your good heart will find its reward soon.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll learn that peace is your best advantage.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s words will stay with you in a good way.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find clarity after a short break.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your quiet confidence will inspire someone.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll realize you’ve already won in small ways.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden moment will sneak into your ordinary day.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll receive the exact motivation you need.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Your laughter today will spark someone’s smile.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find that what you need is already near.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An old worry will fade sooner than you think.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your persistence will open an unexpected door.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll sense a good change in motion.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A friendly gesture will come just when needed.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll discover something beautiful in silence.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’re closer than ever to what you seek.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Your intuition will point you the right way.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll rediscover an old dream with new energy.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will recognize your quiet effort.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your patience will pay off in golden ways.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll feel proud of what you’ve built quietly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A small risk will bring big satisfaction.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll get the answer through a random sign.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A smile you share today will ripple far.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll realize how strong your peace has become.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your heart already knows what’s next.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A calm decision today will turn into a win.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice an unseen benefit of waiting.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will bring unexpected encouragement.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your dedication will soon meet opportunity.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A chance to lead will appear naturally.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll feel harmony return in small moments.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s good news will lift your spirits.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your steady path is stronger than you think.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The next door you open will feel right.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A bit of courage will shift your entire day.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll find wisdom in an ordinary task.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll realize luck favors your kindness.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Your calm tone will resolve a quiet tension.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A small surprise will make your day shine.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll sense balance returning to your week.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your quiet persistence is attracting results.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden moment will confirm your direction.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll soon be thanked for something unseen.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A delayed plan will reveal its purpose.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s calm energy will match yours.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A random act of kindness will circle back.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Your next thought will bring useful clarity.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find joy in giving something simple.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A soft moment will lead to new confidence.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll soon be reminded of your quiet strength.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A friend’s message will mean more than you expect.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll learn patience from an unexpected event.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your warmth will create a good ripple today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A spark of joy will arrive mid-day.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll be proud of what you didn’t give up on.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Someone will mention your name kindly today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your next choice will open a lucky path.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll sense renewal where you least expect it.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A problem will solve itself gently.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice that peace attracts progress.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Your focus will guide others quietly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A moment of laughter will clear the air.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll rediscover joy in a familiar place.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden outcome hides in today’s effort.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Your intuition will lead to comfort soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll get a signal that it’s time to begin again.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll soon feel light after releasing a worry.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s happiness will reflect your effort.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your quiet optimism will inspire change.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll realize your timing was perfect all along.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A good message will arrive at the right hour.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find reward in what you already do well.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll feel peace after speaking kindly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A hidden benefit will soon be revealed.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll feel content with what today brings.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your patience will surprise even you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice your effort paying off quietly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden chance will come disguised as routine.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll sense that something good is unfolding.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your consistency will create unseen blessings.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll notice joy hiding in familiar places.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll soon see proof that your calm matters.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your steady heart draws steady progress.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A small kindness today will echo far ahead.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Someone will notice your quiet confidence.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your effort will shine when timing aligns.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A familiar sound will bring a new idea.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel peace return like sunlight.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Your patience is about to turn into motion.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A new connection will open an unseen path.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll soon experience a moment of effortless clarity.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your care for others will return multiplied.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll rediscover your rhythm in simple things.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A lucky encounter will shift your mood upward.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll receive unexpected encouragement today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your inner calm is becoming unshakable.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A passing thought will reveal deep truth.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll feel more in control than you realize.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A pause will help something fall into place.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your generosity will draw quiet admiration.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice signs that confirm your direction.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Someone you respect will echo your thoughts.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A rare coincidence will remind you of timing’s power.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your positive tone will change the whole mood.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll get news that lightens your day.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A small challenge will turn into your next win.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll realize your influence is stronger than it looks.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An unseen helper is guiding your timing.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll sense harmony forming between plans.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden opportunity will arise from patience.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll feel new lightness after a small decision.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your energy will draw positive encounters.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Something you thought lost will reappear soon.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your best moment will happen without effort.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll turn doubt into quiet confidence.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A random act will change someone’s mood completely.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your next idea will carry a spark of luck.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "The universe is listening to your calm intent.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll notice gratitude growing around you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A peaceful morning will set the tone for your week.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your silent efforts are being quietly celebrated.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll feel a new door open emotionally.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your day will turn out better than expected.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll get validation from a surprising source.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden sign will confirm what you suspected.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll notice that peace itself attracts miracles.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A casual chat will inspire a fresh plan.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your effort will soon feel effortless.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A small joy today will echo for days.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll sense destiny rearranging itself softly.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll receive quiet appreciation soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden moment will unfold naturally today.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll understand why things took their time.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An old habit will fall away effortlessly.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll glimpse the bigger plan through coincidence.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your calm voice will bring comfort soon.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A gentle surprise will reset your perspective.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll be exactly where you need to be.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll feel a guiding presence in quiet moments.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A long-delayed reward is finally moving toward you.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll find joy in doing something for yourself.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone’s honesty will help you move forward.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A strange coincidence will confirm your intuition.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll soon act on an idea that feels just right.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A calm realization will feel like a gift.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your kindness will return faster than expected.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden reward is forming behind the scenes.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll sense the universe syncing with your patience.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A friend’s success will bring you genuine joy.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice how strong you’ve quietly become.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your luck will feel personal today.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A moment of reflection will bring cosmic comfort.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll get a chance to redo something better.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your confidence will attract cooperation.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A hidden blessing is already moving toward you.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll feel time slow when you’re on the right path.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your laughter will make someone’s day easier.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden chance will appear once you relax.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll find purpose in something you nearly gave up.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A dream will feel unusually vivid tonight.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll be surprised how well things align today.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A kind stranger will leave a lasting impression.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll learn that stillness reveals what’s next.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your focus will create golden momentum.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll experience an easy start after rest.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone unseen is wishing you well.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your best idea will come while doing nothing.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A gentle reminder will arrive at the right time.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice signs of progress everywhere.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden outcome hides in today’s patience.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll sense the universe smiling back.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A forgotten joy will return unexpectedly.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your warmth will open a lucky opportunity.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll understand something deeper in silence.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll soon see the reward of being genuine.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden pattern is forming around your effort.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll dream of something that later comes true.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your week will close better than it began.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll feel light after saying the right words.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden calm will fill your next evening.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll soon feel a shift toward balance.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden hour will arrive when you least expect.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll dream of light guiding your next step.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Someone will quote you without realizing it.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll gain clarity while helping another.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A hidden pattern is starting to reveal itself.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your optimism will invite luck today.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A friend’s message will arrive right on time.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find beauty in something unfinished.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "The stars align when your heart is quiet.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A minor delay will turn into a lucky twist.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your calm will inspire someone silently.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll sense guidance through coincidence.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your plans will align with perfect timing.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll laugh at something that once stressed you.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll sense that time bends around purpose.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A forgotten goal will quietly come back.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Someone will recognize your quiet persistence.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A night’s rest will bring a surprising idea.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "The answer you seek will arrive through intuition.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A small win today will boost your whole week.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Your positive thought will ripple outward.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll notice a sign meant only for you.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Someone you admire will mirror your values.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your kindness will open a golden path soon.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "The universe rearranges when you act with trust.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll feel luck growing from consistency.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden realization will brighten your day.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Something once confusing will now feel obvious.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A dream from childhood will resurface gently.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll get noticed for something effortless.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll soon see how far you’ve quietly come.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden message hides in today’s silence.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A strange calm will confirm your intuition.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll end today feeling proud of your patience.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A forgotten song will trigger a happy memory.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden favor will return to you multiplied.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll sense invisible help near your efforts.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A quiet morning will change your perspective.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your steady progress will soon be visible.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "The right word will find you at the right time.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A golden idea will appear between tasks.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll find peace in something you once avoided.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An unseen alignment will ease your next step.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A new routine will bring hidden blessings.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll meet someone whose timing feels fated.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your energy will draw the right person near.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden spark of luck follows your gratitude.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll soon recognize your strength in stillness.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your small choice today will bring long reward.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden moment hides behind today’s pause.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll notice patterns in ordinary moments.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "An unexpected laugh will lighten your energy.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll sense that destiny approves of your plan.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your words today may heal someone quietly.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A golden sense of peace will follow your patience.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll feel universal timing unfold perfectly.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your humor will save the moment.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden turn of events will make you smile.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "An unseen observer admires your growth.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A lucky rhythm is forming in your routine.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "You’ll find delight in something unplanned.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden window of clarity is opening soon.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll receive what you’ve already imagined clearly.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your laughter will attract positive coincidence.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden surprise will align with your timing.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "An ordinary moment will reveal hidden grace.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll notice how peace changes your pace.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A familiar scent will bring unexpected comfort.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your patience will open a golden outcome.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A gentle whisper of destiny surrounds you now.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll soon realize you’re exactly on schedule.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your steady spirit invites golden opportunities.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A vision will confirm your heart’s direction.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll find satisfaction in something simple.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden calm will wrap your evening softly.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "You’ll catch destiny winking in small details.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "A smile from a stranger will feel meaningful.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "Your next idea will unlock golden timing.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A dream symbol will reveal hidden clarity.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll find luck in an unexpected setting.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden word of praise will reach you soon.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "The unseen supports your quiet persistence.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "Your patience today builds tomorrow’s ease.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden sign of progress will appear subtly.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "A soft intuition will guide your next right move.", rarity = FortuneRarity.MYSTIC, isFavorite = false),
                Fortune(text = "You’ll realize how powerful simple trust is.", rarity = FortuneRarity.COMMON, isFavorite = false),
                Fortune(text = "A golden reflection will spark gratitude.", rarity = FortuneRarity.GOLDEN, isFavorite = false),
                Fortune(text = "Your next peaceful breath holds quiet wisdom.", rarity = FortuneRarity.MYSTIC, isFavorite = false)
            )
            fortuneDao.insertAll(initialFortunes)
        }
    }
}
